from SystemPrograms import SystemSetup
from SystemPrograms import TextGeneration
from SystemPrograms import Vision
from SystemPrograms import VoiceGeneration
from SystemPrograms import VoiceRecognition
